# Generated by Django 3.1.1 on 2020-09-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgcompress',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='imgcompress',
            name='img',
            field=models.ImageField(blank=True, upload_to='imgupload/compress/'),
        ),
    ]
